config/routes.rb
Rails.application.routes.draw do
  root to: "application#index"
  resources :paths do
    resources :courses do
      resources :missions
    end
  end

  resources :posts do
    member do
      post :uplike
      post :downlike
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :path
  has_many :posts

  def to_param
    title
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :course

  def to_param
    title
  end

  def finish?
    result = self.if_finish ? "Finished" : "Not Finished"
  end
end

app/models/path.rb
class Path < ApplicationRecord
  has_many :courses
  
  def to_param
    title
  end
end

app/models/post.rb
class Post < ApplicationRecord
  scope :unsort, -> { where(course_id: nil) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/web_scrape.rb
class WebScrape
  attr_reader :img, :favicon, :title, :subtitle, :description, :url

  def initialize(page)
    url_split = page.title.split(/: /)[0].split(/- /)
    markdown = Redcarpet::Markdown.new(MdEmoji::Render, no_intra_emphasis: true)

    @img = page.images.best
    @favicon = page.images.favicon
    @title = url_split[0]
    @subtitle = url_split[1]
    @description = markdown.render(page.description).html_safe
    @url = page.url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :find_course, except: [:new, :create]

  def show
    @posts = @course.posts
  end

  def new
    @path = Path.find_by(title: params[:path_id])
    @course = @path.courses.build
  end

  def edit
  end

  def create
    @path = Path.find_by(title: params[:path_id])
    @course = @path.courses.create(course_params)

    redirect_to path_path(@path)
  end

  def update
    if @course.update(course_params)
      redirect_to path_path(@path)
    else
      render 'edit'
    end
  end

  def destroy
    @course.destroy

    redirect_to path_path(@path)
  end

  private

  def course_params
    params.require(:course).permit(:title, :description)
  end

  def find_course
    @path = Path.find_by(title: params[:path_id])
    @course = Course.find_by(title: params[:id])

    redirect_to path_path(@path) unless @course
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :find_path, :find_course
  before_action :find_mission, except: [:new]

  def show
  end

  def new
    @mission = @course.missions.build
  end

  def edit
  end

  def update
    if @mission.update(mission_params)
      head :no_content
    else
      render 'edit'
    end
  end

  def create
    @mission = @course.missions.create(mission_params)

    redirect_to path_course_path(@path, @course)
  end

  def destroy
    @mission.destroy

    redirect_to path_course_path(@path, @course)
  end

  private

  def mission_params
    params.require(:mission).permit(:title, :description, :url, :if_finish)
  end

  def find_path
    @path = Path.find_by(title: params[:path_id])
  end

  def find_course
    @course = @path.courses.find_by(title: params[:course_id])
  end

  def find_mission
    @mission = @course.missions.find_by(title: params[:id])

    redirect_to path_course_path(@path, @course) unless @course
  end
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  before_action :authenticate_user!

  before_action :find_path, except: [:index, :new, :create]

  def index
    @paths = Path.all
  end

  def show
    @courses = @path.courses
  end

  def new
    @path = Path.new
  end

  def edit
  end

  def create
    @path = Path.new(path_params)

    @path.save
    redirect_to action: :index
  end

  def update
    if @path.update(path_params)
      redirect_to action: :index
    else
      render 'edit'
    end
  end

  def destroy
    @path.destroy

    redirect_to paths_path
  end

  private

  def path_params
    params.require(:path).permit(:title, :description)
  end

  def find_path
    @path = Path.find_by(title: params[:id])

    redirect_to action: :index unless @path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, except: [:index, :new, :create]

  def index
    @posts = Post.unsort
  end

  def show
    page = MetaInspector.new(@post.url)
    @knowledge = WebScrape.new(page)

    render locals: {
      knowledge:  @knowledge
    }
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    @post.save
    redirect_to action: :index
  end

  def update
    if @post.update(post_params)
      redirect_rule
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy

    redirect_rule
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :url, :course_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def find_path_course
    @course = Course.find(@post.course_id)
    @path = Path.find(@course.path_id)
  end

  def redirect_rule
    if @post.course_id?
      find_path_course
      redirect_to path_course_path(@path, @course)
    else
      redirect_to action: :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end
end

app/helpers/paths_helper.rb
module PathsHelper
  def if_finish_all_missions?(course)
    all_missions = course.missions.count
    finished_missions = course.missions.where(if_finish: true).count

    result = (all_missions == finished_missions)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/index.html.erb
<div class="index_div">
  <%= link_to paths_path, class: 'btn btn-outline-primary btn-lg super_lg' do %>
    <span class="glyphicon glyphicon-search"></span>
  <% end %>

  <%= link_to posts_path, class: 'btn btn-outline-success btn-lg super_lg' do %>
    <span class="glyphicon glyphicon-pencil"></span>
  <% end %>
</div>

app/views/courses/_form.html.erb
<%= form_for([@path, @course]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<%= render 'form' %>

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<%= render 'form' %>

app/views/courses/show.html.erb
<div class="jumbotron">
  <h1 class="display-3"><%= @course.title %></h1>
  <p class="lead"><strong><%= @course.description %></strong></p>
  <hr class="m-y-2">
</div>

<table class="table table-hover">
  <thead class="thead-inverse">
    <tr>
      <th> Missions </th>
      <th> Modify </th>
      <th> Delete </th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= link_to post.title, post_path(post) %>
        </td>
        <td>
          <%= link_to 'Modify', edit_post_path(post), class: 'btn btn-outline-warning btn-sm' %>
        </td>
        <td>
          <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary btn-sm' %>
        </td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', path_path(@path), class: 'btn btn-info btn-lg' %>

app/views/layouts/_breadcrumb.html.erb
<nav class="breadcrumb">
  <%= breadcrumbs %>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
  <% if user_signed_in? %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success pull-xs-right' %>
    <%= link_to 'Path', paths_path, class: 'btn btn-outline-warning pull-xs-right' %>
    <%= link_to 'Post', posts_path, class: 'btn btn-outline-info pull-xs-right' %>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-outline-success pull-xs-right' %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TarokoSchool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/navbar" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/missions/_form.html.erb
<%= form_for([@path, @course, @mission]) do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 3, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_area :url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :if_finish %><br>
    <%= f.check_box :if_finish %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/missions/edit.html.erb
<h1>Missions#edit</h1>
<%= render 'form' %>

app/views/missions/new.html.erb
<h1>Missions#new</h1>
<%= render 'form' %>

app/views/missions/show.html.erb
<% breadcrumb :mission , @path, @course, @mission %>
<div class="list-group">
  <p class="list-group-item active">
    <strong><%= @mission.title %></strong>
  </p>
  <p class="list-group-item list-group-item-action">
    <%= @mission.description %>
  </p>
  <%= link_to @mission.url, url_with_protocol(@mission.url), target: '_blank', class: 'list-group-item list-group-item-action' %>
  <p class="list-group-item list-group-item-action">
    <%= @mission.finish? %>
  </p>
  <p class="list-group-item list-group-item-action">
    <%= link_to 'Back', path_course_path(@path, @course), class: 'btn btn-info btn-lg' %>
  </p>
</div>

app/views/paths/_form.html.erb
<%= form_for @path do |f| %>
  <p>
    <%= f.label :Title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/paths/edit.html.erb
<h1>Paths#edit</h1>
<%= render 'form' %>

app/views/paths/index.html.erb
<div class="jumbotron jumbotron_path">
  <h1 class="display-3">Paths</h1>
  <p class="lead">Welcome join the Taroko school.</p>
  <hr class="m-y-2">
  <p class="lead">
    <%= link_to 'Add Path', new_path_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

<div class="card-deck-wrapper card_path_group">
  <% @paths.each_slice(2) do |paths| %>
    <div class="card-deck">
      <% paths.each do |path| %>
        <div class="card text-xs-center card_path">
          <div class="card-header">
            <ul class="nav nav-pills card-header-pills pull-xs-left">
              <li class="nav-item">
                <%= link_to 'Modify', edit_path_path(path), class: 'nav-link', style: 'color: white' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Delete', path_path(path), method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link', style: 'color: white' %>
              </li>
            </ul>
          </div>

          <div class="card-block">
            <h4 class="card-title"><%= link_to path.title, path_path(path) %></h4>
            <p class="card-text"><%= path.description %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/paths/new.html.erb
<h1>Paths#new</h1>
<%= render 'form' %>

app/views/paths/show.html.erb
<div class="jumbotron jumbotron_path">
  <h1 class="display-3"><%= @path.title %></h1>
  <p class="lead"><strong><%= @path.description %></strong></p>
  <hr class="m-y-2">
  <p class="lead">
    <%= link_to 'Add Course', new_path_course_path(@path), class: 'btn btn-primary' %>
  </p>
</div>

<% @courses.each do |course| %>
  <div class="card card-block card_course">
    <h3 class="card-title">
      <%= link_to course.title, path_course_path(@path, course) %>
    </h3>
    <p class="card-text"><%= course.description %></p>
    <%= link_to 'Modify', edit_path_course_path(@path, course), class: 'btn btn-primary' %>
    <%= link_to 'Delete', path_course_path(@path, course), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </div>
<% end %>

<br/>
<%= link_to 'Back', paths_path, class: 'btn btn-info btn-lg' %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 3, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_area :url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Posts</h1>
  <p class="lead">Welcome join the Taroko school.</p>
  <hr class="m-y-2">
  <p class="lead">
    <%= link_to 'Add Post', new_post_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

<table class="table table-hover">
  <thead class="thead-inverse">
    <tr>
      <th>Posts</th>
      <th> Modify </th>
      <th> Delete </th>
      <th> Course </th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= link_to post.title, post_path(post) %>
        </td>
        <td>
          <%= link_to 'Modify', edit_post_path(post), class: 'btn btn-outline-warning btn-sm' %>
        </td>
        <td>
          <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary btn-sm' %>
        </td>
        <td>
          <%= form_for post, method: :patch, remote: true do |f| %>
            <div class="form-group">
              <%= f.collection_select(:course_id, Course.all, :id, :title, {include_blank: "Please select", selected: 0}, html_options = { onchange: "$(this.form).submit()" }) %>
            </div>
          <% end %>
        <td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="list-group">
  <p class="list-group-item active">
    <strong><%= @post.title %></strong>
  </p>
  <p class="list-group-item list-group-item-action">
    <%= @post.description %>
  </p>
  <table class="list-group-item list-group-item-action post_tbl">
    <tr>
      <td colspan="2"><%= link_to @post.url, url_with_protocol(@post.url), target: '_blank' %></td>
    </tr>
    <tr>
      <td>
        <%= image_tag knowledge.favicon unless knowledge.favicon.blank? %><%= knowledge.title %>
      </td>
      <td rowspan="3">
        <%= image_tag knowledge.img, class: "post_img" unless knowledge.img.blank? %>
      </td>
    </tr>
    <tr>
      <td><%= link_to knowledge.subtitle, knowledge.url, target: '_blank' %></td>
    </tr>
    <tr>
      <td><%= knowledge.description %></td>
    </tr>
  </table>
  <p class="list-group-item list-group-item-action">
    <%= link_to 'Back', posts_path, class: 'btn btn-info btn-lg' %>
  </p>
</div>